import { defineConfig, presetUno, presetAttributify, presetIcons } from 'unocss'
import { presetWebFonts } from 'unocss/preset-web-fonts'

export default defineConfig({
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      scale: 1.2,
      cdn: 'https://esm.sh/',
      extraProperties: {
        'display': 'inline-block',
        'vertical-align': 'middle',
      },
    }),
    presetWebFonts({
      provider: 'none',
      fonts: {
        sans: ['SF Pro Display', 'Inter', 'system-ui'],
        heading: ['SF Pro Display', 'Montserrat', 'system-ui'],
        mono: ['SF Mono', 'Fira Code', 'monospace'],
        cyber: ['SF Pro Display', 'BlenderPro', 'system-ui'],
      },
    }),
  ],
  theme: {
    colors: {
      cyber: {
        bg: '#090d1f',
        darkBg: '#0f0f0f',
        text: '#e0e0e0',
        accent: '#bb00ff',
        neon: {
          purple: '#bb00ff',
          blue: '#0088ff',
          cyan: '#00ffff',
          magenta: '#ff00ff',
          lime: '#b4ff00',
          pink: '#ff0066',
          yellow: '#ffdf00',
        },
        glass: {
          border: 'rgba(187, 0, 255, 0.3)',
          bg: 'rgba(15, 15, 31, 0.7)',
          bgLight: 'rgba(25, 25, 45, 0.6)',
        },
      },
      tg: {
        bg: '#ffffff',
        text: '#000000',
        hint: '#999999',
        link: '#2481cc',
        accent: '#007aff',
        button: '#007aff',
        destructive: '#ff3b30',
        secondary: '#8e8e93',
      },
      primary: {
        50: '#eef2ff',
        100: '#e0e7ff',
        200: '#c7d2fe',
        300: '#a5b4fc',
        400: '#818cf8',
        500: '#6366f1',
        600: '#4f46e5',
        700: '#4338ca',
        800: '#3730a3',
        900: '#312e81',
        950: '#1e1b4b',
      },
      secondary: {
        50: '#f5f3ff',
        100: '#ede9fe',
        200: '#ddd6fe',
        300: '#c4b5fd',
        400: '#a78bfa',
        500: '#8b5cf6',
        600: '#7c3aed',
        700: '#6d28d9',
        800: '#5b21b6',
        900: '#4c1d95',
        950: '#2e1065',
      },
      success: {
        50: '#ecfdf5',
        100: '#d1fae5',
        200: '#a7f3d0',
        300: '#6ee7b7',
        400: '#34d399',
        500: '#10b981',
        600: '#059669',
        700: '#047857',
        800: '#065f46',
        900: '#064e3b',
        950: '#022c22',
      },
      danger: {
        50: '#fef2f2',
        100: '#fee2e2',
        200: '#fecaca',
        300: '#fca5a5',
        400: '#f87171',
        500: '#ef4444',
        600: '#dc2626',
        700: '#b91c1c',
        800: '#991b1b',
        900: '#7f1d1d',
        950: '#450a0a',
      },
      dark: {
        900: '#0f172a',
        800: '#1e293b',
        700: '#334155',
        600: '#475569',
        500: '#64748b',
        400: '#94a3b8',
        300: '#cbd5e1',
        200: '#e2e8f0',
        100: '#f1f5f9',
        50: '#f8fafc',
      },
    },
    animation: {
      keyframes: {
        'fade-in': '{0%{opacity:0} 100%{opacity:1}}',
        'fade-out': '{0%{opacity:1} 100%{opacity:0}}',
        'scale-in': '{0%{transform:scale(.95);opacity:0} 100%{transform:scale(1);opacity:1}}',
        'scale-out': '{0%{transform:scale(1);opacity:1} 100%{transform:scale(.95);opacity:0}}',
        'slide-in-right': '{0%{transform:translateX(20px);opacity:0} 100%{transform:translateX(0);opacity:1}}',
        'slide-out-right': '{0%{transform:translateX(0);opacity:1} 100%{transform:translateX(20px);opacity:0}}',
        'slide-in-bottom': '{0%{transform:translateY(20px);opacity:0} 100%{transform:translateY(0);opacity:1}}',
        'slide-out-bottom': '{0%{transform:translateY(0);opacity:1} 100%{transform:translateY(20px);opacity:0}}',
        'slide-in-left': '{0%{transform:translateX(-20px);opacity:0} 100%{transform:translateX(0);opacity:1}}',
        'slide-out-left': '{0%{transform:translateX(0);opacity:1} 100%{transform:translateX(-20px);opacity:0}}',
        'slide-in-top': '{0%{transform:translateY(-20px);opacity:0} 100%{transform:translateY(0);opacity:1}}',
        'slide-out-top': '{0%{transform:translateY(0);opacity:1} 100%{transform:translateY(-20px);opacity:0}}',
        'pulse': '{0%,100%{opacity:1} 50%{opacity:.5}}',
        'breath': '{0%, 100%{transform:scale(1)} 50%{transform:scale(1.05)}}',
        'bounce-soft': '{0%,100%{transform:translateY(0)} 50%{transform:translateY(-5px)}}',
        'glow': '{0%, 100%{filter:drop-shadow(0 0 5px currentColor)} 50%{filter:drop-shadow(0 0 15px currentColor)}}',
        'neon-pulse': '{0%, 100%{filter:drop-shadow(0 0 5px currentColor) drop-shadow(0 0 10px currentColor)} 50%{filter:drop-shadow(0 0 15px currentColor) drop-shadow(0 0 25px currentColor)}}',
        'cyber-breath': '{0%, 100%{box-shadow:0 0 10px currentColor} 50%{box-shadow:0 0 20px currentColor, 0 0 30px currentColor}}',
        'glass-pulse': '{0%, 100%{backdrop-filter:blur(8px); background-opacity:0.1} 50%{backdrop-filter:blur(12px); background-opacity:0.15}}',
        'float': '{0%, 100%{transform:translateY(0)} 50%{transform:translateY(-10px)}}',
      },
      durations: {
        'fade-in': '0.3s',
        'fade-out': '0.3s',
        'scale-in': '0.3s',
        'scale-out': '0.3s',
        'slide-in-right': '0.3s',
        'slide-out-right': '0.3s',
        'slide-in-bottom': '0.3s',
        'slide-out-bottom': '0.3s',
        'slide-in-left': '0.3s',
        'slide-out-left': '0.3s',
        'slide-in-top': '0.3s',
        'slide-out-top': '0.3s',
        'pulse': '2s',
        'breath': '3s',
        'bounce-soft': '2s',
        'glow': '2s',
        'neon-pulse': '3s',
        'cyber-breath': '4s',
        'glass-pulse': '4s',
        'float': '6s',
      },
      timingFns: {
        'fade-in': 'ease-out',
        'fade-out': 'ease-in',
        'scale-in': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'scale-out': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-in-right': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-out-right': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-in-bottom': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-out-bottom': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-in-left': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-out-left': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-in-top': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-out-top': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'pulse': 'cubic-bezier(0.4, 0, 0.6, 1)',
        'breath': 'ease-in-out',
        'bounce-soft': 'ease-in-out',
        'glow': 'ease-in-out',
        'neon-pulse': 'ease-in-out',
        'cyber-breath': 'ease-in-out',
      },
      counts: {
        'pulse': 'infinite',
        'breath': 'infinite',
        'bounce-soft': 'infinite',
        'glow': 'infinite',
        'neon-pulse': 'infinite',
        'cyber-breath': 'infinite',
      },
    },
    breakpoints: {
      xs: '320px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
    fontFamily: {
      sans: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
      serif: 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
      mono: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    },
    extend: {
      boxShadow: {
        'glass': '0 8px 32px rgba(0, 0, 0, 0.1)',
        'glass-sm': '0 2px 8px rgba(0, 0, 0, 0.05)',
        'ios': '0 4px 16px rgba(0, 0, 0, 0.12)',
        'ios-sm': '0 2px 8px rgba(0, 0, 0, 0.08)',
        'ios-inner': 'inset 0 0 5px rgba(0, 0, 0, 0.05)',
        'cyber': '0 0 15px rgba(187, 0, 255, 0.5)',
        'cyber-lg': '0 0 25px rgba(187, 0, 255, 0.7)',
        'neon': '0 0 10px currentColor',
        'neon-lg': '0 0 20px currentColor, 0 0 40px currentColor',
        'glow-light': '0 0 15px rgba(255, 255, 255, 0.4)',
        'glow-cyan': '0 0 15px rgba(0, 255, 255, 0.5)',
        'glow-magenta': '0 0 15px rgba(255, 0, 255, 0.5)',
        'glow-multi': '0 0 10px rgba(255, 255, 255, 0.3), 0 0 20px rgba(120, 115, 245, 0.3), 0 0 30px rgba(255, 110, 196, 0.2)',
      },
      borderRadius: {
        'ios': '10px',
        'ios-xl': '16px',
        'ios-full': '9999px',
        'cyber': '4px',
      },
    },
  },
  shortcuts: {
    'cyber-container': 'w-full max-w-5xl mx-auto p-4 font-sans bg-cyber-darkBg text-cyber-text',
    'cyber-card': 'rounded-cyber backdrop-blur-md bg-cyber-glass-bg border border-cyber-glass-border shadow-cyber transition-all duration-300 hover:shadow-cyber-lg transform hover:scale-102',
    'cyber-card-lg': 'rounded-cyber p-6 backdrop-blur-md bg-cyber-glass-bgLight border border-cyber-glass-border shadow-cyber transition-all duration-300 hover:shadow-cyber-lg transform hover:scale-102',
    'cyber-btn': 'py-2.5 px-5 rounded-cyber transition-all duration-200 transform active:scale-97 select-none font-medium uppercase',
    'cyber-btn-primary': 'cyber-btn bg-gradient-to-r from-cyber-neon-purple to-cyber-neon-blue text-white shadow-neon text-shadow-sm hover:shadow-neon-lg',
    'cyber-btn-accent': 'cyber-btn bg-gradient-to-r from-cyber-neon-magenta to-cyber-neon-cyan text-white shadow-neon text-shadow-sm hover:shadow-neon-lg',
    'cyber-btn-lime': 'cyber-btn bg-gradient-to-r from-cyber-neon-lime to-cyber-neon-cyan text-black shadow-neon text-shadow-sm hover:shadow-neon-lg',
    'cyber-input': 'w-full py-3 px-4 bg-cyber-glass-bg border border-cyber-glass-border rounded-cyber text-cyber-text shadow-neon transition-all duration-200 focus:outline-none focus:border-cyber-neon-purple',
    'cyber-divider': 'h-px bg-gradient-to-r from-transparent via-cyber-neon-purple to-transparent my-4',
    'cyber-title': 'text-2xl font-bold mb-4 text-cyber-text inline-block bg-clip-text text-transparent bg-gradient-to-r from-cyber-neon-cyan to-cyber-neon-purple',
    'cyber-subtitle': 'text-lg font-semibold mb-3 text-cyber-text text-opacity-90',
    'cyber-grid': 'grid grid-cols-1 sm:grid-cols-2 gap-4',
    'cyber-grid-3': 'grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4',
    
    'neon-text': 'text-shadow-neon animate-neon-pulse',
    'neon-text-cyan': 'text-cyber-neon-cyan text-shadow-neon animate-neon-pulse',
    'neon-text-magenta': 'text-cyber-neon-magenta text-shadow-neon animate-neon-pulse',
    'neon-text-lime': 'text-cyber-neon-lime text-shadow-neon animate-neon-pulse',
    'neon-border': 'border-2 border-opacity-80 shadow-neon transition-all duration-300 hover:shadow-neon-lg',
    'neon-border-cyan': 'border-2 border-cyber-neon-cyan border-opacity-80 shadow-neon text-cyber-neon-cyan transition-all duration-300 hover:shadow-neon-lg',
    'neon-border-magenta': 'border-2 border-cyber-neon-magenta border-opacity-80 shadow-neon text-cyber-neon-magenta transition-all duration-300 hover:shadow-neon-lg',
    'neon-border-lime': 'border-2 border-cyber-neon-lime border-opacity-80 shadow-neon text-cyber-neon-lime transition-all duration-300 hover:shadow-neon-lg',
    
    // Temel bileşenler
    'btn': 'py-2.5 px-5 rounded-ios transition duration-200 transform active:scale-97 select-none',
    'btn-primary': 'btn bg-tg-button text-white font-medium hover:bg-blue-600 focus:ring-2 focus:ring-blue-500/50 focus:ring-offset-1',
    'btn-secondary': 'btn bg-gray-200/80 text-gray-800 font-medium hover:bg-gray-300/80 dark:bg-gray-800 dark:text-gray-200 dark:hover:bg-gray-700',
    'btn-danger': 'btn bg-tg-destructive text-white font-medium hover:bg-red-700',
    'btn-tg': 'btn bg-tg-button text-white font-medium active:bg-blue-700',
    'btn-glass': 'btn backdrop-blur-md bg-white/70 dark:bg-dark-800/70 text-gray-800 dark:text-gray-200 hover:bg-white/90 dark:hover:bg-dark-700/90',
    
    // Kart stilleri
    'card': 'rounded-ios-xl p-5 shadow-ios transition-all duration-300 bg-white dark:bg-dark-800',
    'card-glass': 'rounded-ios-xl backdrop-blur-md bg-white/80 dark:bg-dark-800/80 shadow-glass border border-white/20 dark:border-dark-700/30 p-5 transition-all duration-300',
    'card-glass-sm': 'rounded-ios backdrop-blur-md bg-white/80 dark:bg-dark-800/80 shadow-glass-sm border border-white/20 dark:border-dark-700/30 p-4 transition-all duration-300',
    'card-flat': 'rounded-ios-xl bg-gray-100/50 dark:bg-dark-700/50 p-5 transition-all duration-300',
    'card-tg': 'rounded-ios-xl bg-white dark:bg-[#18222d] shadow-ios p-5 transition-all duration-300',
    
    // Gradient arka planlar
    'gradient-bg': 'bg-gradient-to-br from-blue-50/70 to-purple-50/70 dark:from-dark-800/70 dark:to-dark-900/70',
    'gradient-tg': 'bg-gradient-to-r from-tg-button to-blue-500',
    'gradient-text': 'bg-clip-text text-transparent bg-gradient-to-r from-blue-500 to-purple-600 dark:from-blue-400 dark:to-purple-400',
    
    // Form bileşenleri
    'input-field': 'w-full py-2.5 px-4 bg-white/90 dark:bg-dark-800/90 border border-gray-300/60 dark:border-dark-700/60 rounded-ios shadow-ios-inner focus:outline-none focus:ring-2 focus:ring-tg-accent focus:border-tg-accent transition-all duration-200',
    'input-tg': 'w-full py-3 px-4 bg-gray-100 dark:bg-[#242f3d] rounded-ios text-black dark:text-white transition-all duration-200 focus:outline-none focus:bg-gray-50 dark:focus:bg-[#20293a]',
    
    // Telegram Mini App özel stilleri
    'tg-container': 'w-full max-w-md mx-auto p-4 font-sans text-tg-text dark:text-white',
    'tg-title': 'text-xl font-bold mb-4 text-tg-text dark:text-white',
    'tg-subtitle': 'text-lg font-semibold mb-3 text-tg-text dark:text-white',
    'tg-text': 'text-base text-tg-text dark:text-white',
    'tg-hint': 'text-sm text-tg-hint dark:text-gray-400',
    'tg-link': 'text-tg-link dark:text-blue-400 hover:underline',
    'tg-divider': 'h-px bg-gray-200 dark:bg-gray-700 my-4',
    
    // Duyarlı grid
    'tg-grid': 'grid grid-cols-1 sm:grid-cols-2 gap-4',
    'tg-grid-3': 'grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4',
    
    // Liste öğeleri
    'tg-list-item': 'flex items-center p-3 border-b border-gray-100 dark:border-gray-800 last:border-0',
    'tg-avatar': 'w-10 h-10 rounded-full bg-gray-200 dark:bg-gray-700 overflow-hidden',
    
    // Animasyonlar
    'animate-breath': 'animate-breath',
    'animate-bounce-soft': 'animate-bounce-soft',
    'animate-glow': 'animate-glow',
    'animate-cyber-breath': 'animate-cyber-breath',
    
    // Yeni eklenen animasyonlu kartlar
    'animated-card': 'rounded-xl backdrop-blur-md bg-white/10 border border-white/30 shadow-lg transition-all duration-300 hover:shadow-glow-light hover:scale-102',
    'animated-card-cyan': 'rounded-xl backdrop-blur-md bg-white/10 border border-cyan-500/30 shadow-lg transition-all duration-300 hover:shadow-glow-cyan hover:scale-102',
    'animated-card-magenta': 'rounded-xl backdrop-blur-md bg-white/10 border border-fuchsia-500/30 shadow-lg transition-all duration-300 hover:shadow-glow-magenta hover:scale-102',
    'animated-card-float': 'rounded-xl backdrop-blur-md bg-white/10 border border-white/30 shadow-lg transition-all duration-300 hover:shadow-glow-light hover:scale-102 animate-float animate-count-infinite animate-duration-6s',
    
    // Sayfa geçiş animasyonları için container
    'page-transition-container': 'w-full h-full min-h-screen transition-all duration-500',
  },
})
